language: php

env:
  global:
    - deps=""
    - COMPOSER_OPTIONS="--prefer-stable"

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: $COMPOSER_OPTIONS="--prefer-lowest --prefer-stable --ignore-platform-reqs"
    - php: 7.1
      env: PACKAGES="php-http/discovery:^1.0 php-http/guzzle6-adapter:^1.0 php-http/message:^1.0 xabbuh/oauth1-authentication:~1.0"
    - php: 7.1
      env: xdebug="yes"
    - php: 7.2
    - php: 7.3

install:
  - if [ "$PACKAGES" != "" ]; then composer require --no-update $PACKAGES; fi
  - composer update $COMPOSER_OPTIONS

script:
  - if [[ "$xdebug" = "yes" ]]; then vendor/bin/phpunit --coverage-clover=coverage.clover; else vendor/bin/phpunit; fi
  - if [[ "$xdebug" = "yes" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$xdebug" = "yes" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
